application:
  title: Webflux & Mongodb Test application
  version: 1.0

server:
  port: 8080
  tomcat:
    max-connections: 10000
    max-threads: 300
    accept-count: 300
    min-spare-threads: 50

#mongo:
#  uri: mongodb://localhost:27017
spring:
  webflux:
    base-path: /api
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: local

  mongodb:
    embedded:
      version: 3.6.0   #  mongodb:
#    embedded:
#      version: 3.6.22

  redis:
    host: localhost
    port: 6379
  profiles:
    active: local

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    io:
      netty: DEBUG
    com:
      bithumbsystems:
        bootstarterproject: DEBUG
    org:
      springframework:
        data: TRACE
    reactor:
      core: TRACE
      util: TRACE

endpoints:
  health:
    enabled: true
  metrics:
    enabled: true
